# Generated by Django 5.0.4 on 2024-09-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('username', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
